/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'START OVER': '重来',
    'BEGIN': '开始',
    'Continue': '继续',
    'Annihilate a Positron for 1+ Charge': '消灭一个带1+电荷的电子',
    'Annihilate a Positron for 1- Charge': '消灭一个带1-电荷的电子',
    'THE END': '通关',
    'Swap Charges': '互换费用',
    'The previous news ticker was a lie.': '之前的新闻播报是一个谎言。',
    'The universe has been cast in darkness for ages...': '宇宙多年来一直处于黑暗之中。',
    'There\'s no ehehe minigame here, so don\'t bother checking.': '这里没有 ehehe 小游戏，所以不要费心检查。',
    'ESCAPE': '逃离',
    'FROM': '',
    'VANTABLACK': '黑暗',
    'Let there be light!': '要有光！',
    'Mind Boost': '心灵提升',
    'Mind+': '心灵+',
    'Strength Boost': '力量提升',
    'Strength+': '力量+',
    'Whenever anyone says an ellipsis by itself, don\'t you just wanna consider it as them having no idea what to say and throwing up? Was this an original joke? I dunno, but maybe it\'s a Game Theory reference or something i dunno...': '每当有人单独说省略号时，您难道不只是想将其视为他们不知道该说什么而呕吐吗？ 这是一个原创的笑话吗？ 我不知道，但也许这是一个博弈论参考或我不知道的东西......',
    'Currently': '当前',
    'Main': '主要',
    'Quadruple Photon Automaton speed': '四倍光子自动速度',
    'Split the Photon interval in half': '将光子间隔一分为二',
    'The dimensions here are not made of antimatter. If they were, your face would have melted off years ago.': '这里的维度不是由反物质构成的。 如果是的话，你的脸在几年前就已经融化了。',
    'Triple Photon gain': '三重光子增益',
    'gets disemboweled': '被开膛破肚',
    'If you can see this, why are you chilling on this menu? Cmon, press that button that says \"BEGIN\"!': '如果你能看到这个，你为什么对这个菜单不寒而栗？ 拜托，按下那个写着“开始”的按钮！',
    'Just one more news ticker!': '又多了一个新闻自动收报机！',
    'Reach 100,000,000 Total Photons to begin the process of Pair Production': '达到100,000,000光子总数，开始偶产生进程',
    'Double Photon Upgrade 3\'s effect': '双光子升级3的效果',
    'Annihilate an Electron for 1+ Charge': '消灭一个电子获得带1+电荷',
    'Raise the Lumen effect': '提高流明效果',
    'Photons boost their own gain': '光子提升自身增益',
    'Pair Production requirement is divided by {{formatWhole(tmp.stre)}}, and Mind/Strength progress gain is multiplied by {{format(tmp.stre2)}}': '偶产生 需求除以{{formatWhole(tmp.stre)}}，心灵/力量 进度增益乘以{{format(tmp.stre2)}}',
    'Options': '选项',
    'Growth': '成长',
    'Pair Production': '偶产生',
    'You have {{formatWhole(player.truePhotons)}} True Photons, which are multiplying Photon gain by {{format(tmp.tphe)}}': '你有 {{formatWhole(player.truePhotons)}} 真光子，它们是将光子增益乘以 {{format(tmp.tphe)}}',
    'Add 1 to the bases of Photon Upgrades 3 & 5': '在 光子 升级 3 和 5 的基础上添加 1',
    'Are these news ticker messages just out-of-context texts that my friends have sent me? I don\'t know, but you can safely say that this one isn\'t. Right?': '这些新闻快讯是否只是我的朋友发给我的脱离上下文的文本？ 我不知道，但你可以有把握地说这不是。 正确的？',
    'Due to the presence of Vantablack in this universe, your Photons, Total Photons, & Photon gain are being divided by {{format(player.reversalDiv)}} every second, and you can no longer create Photons manually.': '由于这个宇宙中存在 黑暗，你的光子、总光子和光子增益每秒都被 {{format(player.reversalDiv)}} 除，你不能再手动创建光子。',
    '\t\t\t\t\tNext Pair Production at {{formatWhole(tmp.npp)}} Total Photons': '\t\t\t\t\t新的 偶产生 在 {{formatWhole(tmp.npp)}} 总光子',
    '\t\t\t\tCurrent Boost Effect: Increase the True Photon effect exponent by {{format(Decimal.pow(1.2, player.truePhotBought).sub(Decimal.pow(1.4, player.badTruePhotBought)).times(100))}}% & increase its gain speed by {{format(Decimal.pow(1.01, player.truePhotBought-player.badTruePhotBought).sub(1).times(100))}}': '\t\t\t\tCurrent Boost Effect: 增加真实光子效果指数 {{format(Decimal.pow(1.2, player.truePhotBought).sub(Decimal.pow(1.4, player.badTruePhotBought)).times(100 ))}}% & 增加它的获取速度 {{format(Decimal.pow(1.01, player.truePhotBought-player.badTruePhotBought).sub(1).times(100))}}',
    '\t\t\t\tPhoton Production Rate': '\t\t\t\t光子产生率',
    ': {{format(tmp.lum)}}, which multiply Photon gain by {{format(tmp.lumEff)}}': '：{{format(tmp.lum)}}，将光子增益乘以{{format(tmp.lumEff)}}',
    'Lumen Upgrades 1 & 2 are given {{format(tmp.mnde)}} extra levels, and the Mind/Strength Automaton is {{format(tmp.mnde2)}}x faster': '流明升级 1 和 2 被赋予 {{format(tmp.mnde)}} 额外等级，并且心灵/力量自动变快 {{format(tmp.mnde2)}}x',
    'I\'d recommend exporting your current state of existence to the network before filling the universe with photons entirely, with 100% fill completion. Just in case you regret your decision and want to let it sink into darkness. Nobody likes a bright light in their eyes all the time, right?': '我建议在用光子完全填充宇宙之前将您当前的存在状态导出到网络，100% 填充完成。 以防万一你后悔你的决定并想让它陷入黑暗。 没有人喜欢眼睛里一直有明亮的光，对吧？',
    '{{player.autosave?\"ON\":\"OFF\"}}': '{{player.autosave?\"开启\":\"关闭\"}}',
    '{{player.charge.eq(0)?\"None\":(player.charge.gt(0)?(\"Add \"+format(tmp.crge)+\" Levels to Photon Upgrade 3 & 5\"):(\"Add \"+format(tmp.crge)+\" Levels to Photon Upgrade 2 & 4\"))}}': '{{player.charge.eq(0)?\"无\":(player.charge.gt(0)?(\"增加 \"+format(tmp.crge)+\" 等级到光子升级 3 & 5\"):(\"增加 \"+format(tmp.crge)+\" 等级到光子升级 2 & 4\"))}}',
    ' boost Mind/Strength XP gain': '提升心灵/力量 经验 增益',
    'Mind & Strength add levels to Lumen Upgrade 3 & Photon Upgrade 9': '心灵与力量为流明升级 3 和光子升级 9 添加等级',
    'Mind/Strength\'s secondary boost bases are increased by 1': '心灵/力量的辅助提升基础增加1',
    'Ow the photons are hurting my eyes.': '哦，光子正在伤害我的眼睛。',
    'Quadruple Photon gain': '四倍光子增益',
    'Quadruple Photon Upgrade 3\'s effect': '四重光子升级3的效果',
    'Quintuple Photon Automaton speed': '五倍光子自动速度',
    'Sextuple Photon Automaton speed': '六倍光子自动速度',
    'Triple Photon Upgrade 3\'s effect': '三重光子升级3的效果',
    'Split the Photon interval in fourths': '将光子间隔拆分为四份',
    'Split the Photon interval in thirds': '将光子间隔分成三份',
    'In order to survive your journey with style, you need 20 degrees in Quantum Physics & Photonics.': '为了以时尚的方式在您的旅程中生存，您需要 20 度的量子物理和光子学。',
    'Quintuple Photon Upgrade 3\'s effect': '五重光子升级3的效果',
    'Septuple Photon Automaton speed': '七重光子自动速度',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Total: ": "总计: ",
    "STRENGTH: ": "力量: ",
    "Level ": "等级 ",
    "MIND: ": "心灵: ",
    "Multiply Photon gain by ": "将光子增益乘以",
    "Positrons: ": "正电子：",
    'Lumens': '流明',
    "Net Charge: ": "净电荷：",
    "Electrons: ": "电子：",
    "Effect: ": "效果: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)ms$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.,]+)e([\d\.,]+) Photons$/, '$1e$2 光子'],
    [/^([\d\.,]+) Photons$/, '$1 光子'],
    [/^Add (.+) to Photon Upgrade (.+)\'s base effect$/, '将 $1 添加到 光子升级 $2 的基础效果'],
    [/^Add (.+) to Photon Upgrade (.+)\'s base$/, '添加 $1 到 光子升级 $2 的基础'],
    [/^Cost: (.+) Photons$/, '成本: $1 光子'],
    [/^Req: (.+) Lumens$/, '要求: $1 流明'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);